import StoryblokProvider from "@/components/StoryblokProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const linkClass = "flex items-center h-20 px-5";

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased pb-10`}
        >
          <header className="bg-blue-200 mb-10">
            <div className="grid grid-cols-2">
              <Link href="/" className={`${linkClass} font-bold text-xl`}>Team H</Link>
              <ul className="flex justify-end">
                <li><Link className={linkClass} href="/">Home</Link></li>
                <li><Link className={linkClass} href="/about">About</Link></li>
                <li><Link className={linkClass} href="/contact">Contact</Link></li>
              </ul>
            </div>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
